---
title: "LMSz"
format: html
warning: false
message: false
---

```{r}
source("util_scripts/R_util.R")
library(gamlss)
library(gamlssTools)
source("gamlss/102.gamlss-recode.r")
source("gamlss/301.functions.r")
set.seed(2514)
```

## Load CHOP Data

```{r}
load('data/analysis_prep_combined.RData')
slip_features <- read_csv("data/CHOP/pheno_dict.csv", show_col_types = F)
```

```{r}
# Add longitudinal data for LMSz modeling
df <- bind_rows(df, df.long) %>%
       filter(dx == "22q11DS", Source == "CHOP") %>%
       arrange(!is.na(main_analysis)) %>%
       mutate(across((contains("CT.") | contains("meanCT")), ~ ifelse(age_years < 2, NA, .x)),
              across((contains("CT.") | contains("meanCT"))
                     & contains("normalised"), ~ .x*10000)) %>%
       distinct(participant, AgeTransformed, sex, .keep_all = T)

# Remove duplicates and scans with pathology
# Calculate weights based on the number of longitudinal obs
df.long$long <- TRUE
df <- left_join(df,df.long %>% select(participant, AgeTransformed, long)) %>%
          mutate(long = !is.na(long)) %>%
          filter(pathology == "Normal") %>% 
                add_count(participant) %>%
                mutate(weight = 1/n)
```

## Generate LMSz Growth Charts

```{r}
# Define LMSz models to process
# Mean (mu) models
m_models = c('~ AgeTransformed + sex + AgeTransformed*sex',
             '~ AgeTransformed + sex',
             '~ AgeTransformed',
             '~ sex',
             '~ 1',
             '~ 0')

# Variance (sigma) models
s_models = c('~ AgeTransformed + sex',
             '~ AgeTransformed',
             '~ sex',
             '~ 0')
```

```{r}
#| results: false
dir.create("lmsz/lmsz_models_slip", recursive = T)

slip_worm_plots <- list()
# Create tibble to hold best model
models <- tibble(feature = features,
                 m_model = "",
                 s_model = "",
                 AIC = NA,
                 BIC = 999999999999,
                 age_coef = NA,
                 sex_coef = NA,
                 intercept_coef = NA,
                 interaction_coef = NA,
                 age_sigma_coef = NA,
                 sex_sigma_coef = NA,
                 intercept_sigma_coef = NA,
                 interaction_sigma_coef = NA)

# Build the growth chart model
p <- "zscore" # specify the phenotype
for (pheno in features) {
  # Define phenotype
  print(pheno)
  pheno_name <- glue("{pheno}Transformed.q.wre")
  zscore_name <- glue("{pheno}Transformed.q.zscore")
  old_pheno <- slip_features$old_pheno[slip_features$new_pheno == pheno]
  # Load reference SLIP fit model
  if (grepl("CT",pheno)) {
      orig_fit <- readRDS(glue("gamlss/RDS/joint_mpr-{old_pheno}Transformed/FIT.EXTRACT.rds"))
  } else {
      orig_fit <- readRDS(glue("gamlss/RDS/joint_median-{old_pheno}Transformed/FIT.EXTRACT.rds"))
  }
  
  # Make subset
  df_tmp <- df %>%
              select(participant, AgeTransformed, sex, weight, 
                     age_years, Deletion_Type,
                     !!pheno_name, !!zscore_name) %>%
              rename(pheno = !!pheno_name,
                     zscore = !!zscore_name) %>%
              na.omit()
  
  # Loop through each mu and sigma model
  mod <- models$feature == pheno
  for (m in m_models) {
    for (s in s_models) {
      print(m)
      print(s)
      
      # Run preliminary model - all subjects
      growthChartModel_all <- gamlss(formula = as.formula(glue("zscore {m}")),
                                     sigma.formula = as.formula(glue("zscore {s}")),
                                     family = NO,
                                     data = df_tmp,
                                     weights = df_tmp$weight,
                                     control = gamlss.control(n.cyc = 200),  # See (2)
                                     trace = F)
      
      # Re-weight observations to exclude individuals with large residuals (> 3.5)
      df_tmp$weight_tmp <- df_tmp$weight
      df_tmp$weight_tmp[which(abs(resid(growthChartModel_all)) > 3.5)] <- 0
      
      # Run refined model
      growthChartModel <- gamlss(formula = as.formula(glue("zscore {m}")),
                                     sigma.formula = as.formula(glue("zscore {s}")),
                                     family = NO,
                                     data = df_tmp,
                                     weights = df_tmp$weight_tmp,
                                     control = gamlss.control(n.cyc = 500),
                                     trace = F)
      
      # Check if the model has the lowest BIC and record it
      if (growthChartModel$sbc <= models$BIC[mod]) {
        fin_model <- growthChartModel
        models$m_model[mod] <- m
        models$s_model[mod] <- s
        models$BIC[mod] <- growthChartModel$sbc
      }
      print("--------------")
    }
  }
  
  # Refine formatting of final models
  models$m_model[mod] <- format(fin_model$mu.formula)
  models$s_model[mod] <- format(fin_model$sigma.formula)
  
  # Extract model coefficients - mu
  models$intercept_coef[mod]   <- fin_model$mu.coefficients["(Intercept)"]
  models$age_coef[mod]         <- fin_model$mu.coefficients["AgeTransformed"]
  models$sex_coef[mod]         <- fin_model$mu.coefficients["sexMale"]
  models$interaction_coef[mod] <- fin_model$mu.coefficients["AgeTransformed:sexMale"]
  # Extract model coefficients - sigma
  models$intercept_sigma_coef[mod]   <- fin_model$sigma.coefficients["(Intercept)"]
  models$age_sigma_coef[mod]         <- fin_model$sigma.coefficients["AgeTransformed"]
  models$sex_sigma_coef[mod]         <- fin_model$sigma.coefficients["sexMale"]
  models$interaction_sigma_coef[mod] <- fin_model$sigma.coefficients["AgeTransformed:sexMale"]

  # Extract final AIC/BIC
  models$AIC[mod] <- fin_model$aic
  models$BIC[mod] <- fin_model$sbc
  
  # Save final model
  saveRDS(fin_model,glue("lmsz/lmsz_models_slip/SLIP_lmsz_{old_pheno}Transformed.rds"))

  # Update LMSz quantiles
  df_tmp <- df_tmp %>%
        add_column(!!glue("{pheno}Transformed.q.lmsz") := pred_og_centiles(growthChartModel,
                                                                          df_tmp)) %>%
        select(-c(pheno, zscore, age_years, Deletion_Type, weight))
  
  # Add LMSz centile to final dataframe
  df <- df %>% left_join(df_tmp, by = join_by(participant, sex, AgeTransformed))
  
  # Save worm plot
  slip_worm_plots[[pheno]] <- wp.taki(fin_model) +
                                  ggtitle("LMSz Worm Plot") +
                                  theme_pubr() +
                                  theme(plot.title = element_text(size = 12),
                                        axis.title = element_text(size = 12))

  
  print("-------------------------")
}

```

```{r}
# CT.rh_superiorparietal is an outlier exclude it
models[models$feature == "CT.rh_superiorparietal",c("AIC","BIC",colnames(models)[grepl("_coef",colnames(models))])] <- NA
```

### Save Models and Centiles

```{r}
write_csv(models, "tables/supplementary_table_lmsz_models.csv")
write_csv(df,"additional_tables/CHOP_lmsz_adjusted_idps.csv")
```

## Backtransform Centiles

```{r}
#| results: false
for (pheno in features) {
  print(pheno)
  tmp <-  backtransform_centile_fans(pheno)
  if (pheno == features[1]) {
    out_fans_slip <- tmp
  } else {
    out_fans_slip <- bind_rows(out_fans_slip, tmp)
  }
}
```

```{r}
# CT scale is off and eTIV fans are doubled. Provide manual correction
out_fans_slip <- out_fans_slip %>% 
                          mutate(SLIP_input_fans = ifelse(grepl("CT",pheno),
                                                          SLIP_input_fans*10000,
                                                          SLIP_input_fans),
                                 LMSz_fans = ifelse(grepl("CT",pheno),
                                                          LMSz_fans*10000,
                                                          LMSz_fans)) %>% 
                          mutate(SLIP_input_fans = ifelse(pheno == "eTIV",
                                                          SLIP_input_fans/2,
                                                          SLIP_input_fans),
                                 LMSz_fans = ifelse(pheno == "eTIV",
                                                          LMSz_fans/2,
                                                          LMSz_fans))
```

# Generate Plots

## Plot SLIP and LMSz Global Trajectories

```{r}
x_breaks <- log(c(280, 365.25*1+280, 365.25*2+280, 
                  365.25*6+280, 365.25*21+280))
x_labs <- c("0y","1y","2y","6y","21y")
```

```{r, fig.height = 7.5, fig.width = 11}
#| output: false

slip_plots <- list()
lmsz_plots <- list()
mult <- 1
out_fans_plot <- out_fans_slip
for (pheno_of_int in c("eTIV","Ventricles","GMV","Cerebellum.all",
                       "sGMV","totalSA","WMV","meanCT")) {
  df_plot <- df
  df_plot$pheno <- df_plot[[glue("{pheno_of_int}Transformed.normalised")]]
  df_plot$pheno[is.na(df_plot[[glue("{pheno_of_int}Transformed.q.lmsz")]])] <- NA
  if (grepl("SA",pheno_of_int)) {
    ylab_text <- bquote('Surface Area')
  } else if (grepl("CT",pheno_of_int)) {
    ylab_text <- bquote('Thickness')
    df_plot <- df_plot %>% filter(age_days >= 2*365.25+280) ### BRING FURTHER UP????
  } else {
    ylab_text <- bquote('Volume')
  }
  if(pheno_of_int == "totalSA") {
    pheno_label <- "Cortical Surface Area"
  } else if (pheno_of_int == "meanCT") {
    pheno_label <- "Mean Cortical Thickness"
  } else if (pheno_of_int == "eTIV") {
    pheno_label <- "Intracranial Volume"
  } else if (pheno_of_int == "Cerebellum.all") {
    pheno_label <- "Cerebellum"
  } else if (pheno_of_int == "GMV") {
    pheno_label <- "Gray Matter Volume"
  } else if (pheno_of_int == "sGMV") {
    pheno_label <- "Subcortical Gray Matter Volume"
  } else if (pheno_of_int == "WMV") {
    pheno_label <- "White Matter Volume"
  } else {
    pheno_label <- pheno_of_int
  }
  out_fans_plot <- out_fans_slip %>% 
                    filter(pheno == pheno_of_int,
                           !(centile_cat %in% c("cent_0.25", "cent_0.75"))) %>%
                    mutate(SLIP_input_fans = SLIP_input_fans*mult,
                           LMSz_fans = LMSz_fans*mult)
  # CT data is questionable at 0y. Limit to 2 years
  if (grepl("CT",pheno_of_int)) {
    df_plot <- df_plot %>% filter(age_days >= 2*365.25+280)
    out_fans_plot <- out_fans_plot %>% filter(AgeTransformed >= log(2*365.25+280))
  }
  slip_plots[[pheno_of_int]] <- ggplot(out_fans_plot) +
                                    geom_point(data = df_plot, aes(y = pheno,
                                               x = AgeTransformed, fill=sex), 
                                               alpha=0.5, shape=21, size = 0.5) +
                                    geom_line(aes(x = AgeTransformed, y = SLIP_input_fans,
                                                  group = interaction(centile_cat, sex),
                                                  color = sex,
                                                  linewidth = line_size,
                                                  linetype = line_type)) +
                                    scale_linewidth_identity() +
                                    scale_linetype_identity() +
                                    scale_colour_manual(values = c("firebrick","royalblue")) +
                                    scale_x_continuous(breaks = x_breaks, labels = x_labs) +
                                    ggtitle(pheno_label) + theme_pubclean() +
                                    xlab("") + ylab(ylab_text) +
                                  theme(plot.title = element_text(size = 12),
                                        axis.title = element_text(size = 10),
                                        axis.text = element_text(size = 8))

  lmsz_plots[[pheno_of_int]] <- ggplot(out_fans_plot) +
                                    geom_point(data = df_plot, aes(y = pheno,
                                               x = AgeTransformed, fill=sex), 
                                               alpha=0.5, shape=21, size = 0.5) +
                                    geom_line(aes(x = AgeTransformed, y = LMSz_fans,
                                                  group = interaction(centile_cat, sex),
                                                  color = sex,
                                                  linewidth = line_size,
                                                  linetype = line_type)) +
                                    scale_linewidth_identity() +
                                    scale_linetype_identity() +
                                    scale_colour_manual(values = c("firebrick","royalblue")) +
                                    scale_x_continuous(breaks = x_breaks, labels = x_labs) +
                                    theme_pubclean() +
                                    xlab("") + ylab(ylab_text) +
                                  theme(plot.title = element_text(size = 12),
                                        axis.title = element_text(size = 10),
                                        axis.text = element_text(size = 8))
  
  # Equalize Axes
  p_y_min <- min(layer_scales(slip_plots[[pheno_of_int]])$y$range$range[1],
                 layer_scales(lmsz_plots[[pheno_of_int]])$y$range$range[1])
  p_y_max <- max(layer_scales(slip_plots[[pheno_of_int]])$y$range$range[2],
                 layer_scales(lmsz_plots[[pheno_of_int]])$y$range$range[2])

  slip_plots[[pheno_of_int]] <- slip_plots[[pheno_of_int]] + ylim(p_y_min,p_y_max)
  lmsz_plots[[pheno_of_int]] <- lmsz_plots[[pheno_of_int]] + ylim(p_y_min,p_y_max)
}
p1_title <- ggdraw() + draw_label("Original (SLIP)", angle = 90,
                                  x = 0.5, hjust = 0.5, fontface = "bold")
p1 <- ggarrange(plotlist =  slip_plots, nrow = 1, legend = "none", common.legend = T)
p2_title <- ggdraw() + draw_label("22q LMSz", angle = 90,
                                  x = 0.5, hjust = 0.5, fontface = "bold")
p2 <- ggarrange(plotlist =  lmsz_plots, nrow = 1, legend = "bottom", common.legend = T)
p_fits <- ggarrange(p1_title, p1, 
                p2_title, p2, 
                nrow = 2, ncol = 2, widths = c(0.1,1.2),
                legend = "bottom", common.legend = T)

```

```{r, fig.height = 7.5, fig.width = 11}
p_fits
```

## Plot Overlaid Trajectories

```{r}
#| output: false
# eTIV, WMV, GMV, sGMV, totalSA, meanCT

overlap_plots_male <- list()
overlap_plots_female <- list()
overlap_plots_deriv <- list()
out_fans_plot <- out_fans_slip
for (pheno_of_int in c("eTIV","Ventricles","GMV","Cerebellum.all",
                       "sGMV","totalSA","WMV","meanCT",
                       "SA.medialorbitofrontal", "SA.lateraloccipital",
                       "SA.postcentral","SA.superiorparietal",
                       "SA.transversetemporal","SA.rostralanteriorcingulate")) {
  df_plot <- df
  df_plot$pheno <- df_plot[[glue("{pheno_of_int}Transformed.normalised")]]
  if (grepl("SA",pheno_of_int)) {
    ylab_text <- bquote('Surface Area')
    mult <- 1
  } else if (grepl("CT",pheno_of_int)) {
    ylab_text <- bquote('Thickness')
    mult <- 1
  } else {
    ylab_text <- bquote('Volume')
    mult <- 1
  }
  if (pheno_of_int == "eTIV") {
    pheno_renamed <- "Intracranial Volume"
  } else if (pheno_of_int == "Cerebellum.all") {
    pheno_renamed <- "Cerebellum"
  } else {
    pheno_renamed <- pheno_of_int
  }
  
  out_fans_plot <- out_fans_slip %>% 
                    filter(pheno == pheno_of_int,
                           !(centile_cat %in% c("cent_0.25", "cent_0.75"))) %>%
                    mutate(SLIP_input_fans = SLIP_input_fans*mult,
                           LMSz_fans = LMSz_fans*mult)
  if (grepl("CT",pheno_of_int)) {
    df_plot <- df_plot %>% filter(age_days >= 2*365.25+280)
    out_fans_plot <- out_fans_plot %>% filter(AgeTransformed >= log(2*365.25+280))
  }
  overlap_plots_male[[pheno_of_int]] <- ggplot(out_fans_plot %>% filter(sex == "Male")) +
                                    geom_line(aes(x = AgeTransformed, y = SLIP_input_fans,
                                                  group = centile_cat,
                                                  color = "SLIP",
                                                  linewidth = line_size,
                                                  linetype = line_type)) +
                                    geom_line(aes(x = AgeTransformed, y = LMSz_fans,
                                                  group = centile_cat,
                                                  color = "LMSz",
                                                  linewidth = line_size,
                                                  linetype = line_type)) +
                                    scale_linewidth_identity() +
                                    scale_linetype_identity() +
                                    scale_x_continuous(breaks = x_breaks, labels = x_labs) +
                                    ggtitle(pheno_of_int) + theme_pubclean() +
                                    xlab("") + ylab(ylab_text) +
                                    scale_colour_manual(values = c("black", "grey")) +
                                    theme(plot.title = element_text(size = 12),
                                          axis.title = element_text(size = 10),
                                          axis.text = element_text(size = 8))
  
  overlap_plots_female[[pheno_of_int]] <- ggplot(out_fans_plot %>% filter(sex == "Female")) +
                                      geom_line(aes(x = AgeTransformed, y = SLIP_input_fans,
                                                    group = centile_cat,
                                                    color = "SLIP",
                                                    linewidth = line_size,
                                                    linetype = line_type)) +
                                      geom_line(aes(x = AgeTransformed, y = LMSz_fans,
                                                    group = centile_cat,
                                                    color = "LMSz",
                                                    linewidth = line_size,
                                                    linetype = line_type)) +
                                      scale_linewidth_identity() +
                                      scale_linetype_identity() +
                                      scale_x_continuous(breaks = x_breaks, labels = x_labs) +
                                      ggtitle(pheno_of_int) + theme_pubclean() +
                                      xlab("") + ylab(ylab_text) +
                                      scale_colour_manual(values = c("black", "grey")) +
                                      theme(plot.title = element_text(size = 12),
                                            axis.title = element_text(size = 10),
                                            axis.text = element_text(size = 8))
  out_fans_plot_avg <-   out_fans_plot %>% 
                          filter(grepl(str_replace_all(pheno_of_int,"SA.","SA.*"),pheno),
                                 !(centile_cat %in% c("cent_0.25", "cent_0.75"))) %>%
                          mutate(SLIP_input_fans = SLIP_input_fans*mult,
                                 LMSz_fans = LMSz_fans*mult) %>%
                          group_by(model, AgeTransformed, 
                                   centile_cat, line_size, line_type) %>%
                          summarize(across(contains("fans"), ~mean(.x, na.rm = T)))
  
  overlap_plots_deriv[[pheno_of_int]] <- ggplot(out_fans_plot_avg) +
                                    geom_line(aes(x = AgeTransformed, y = SLIP_input_fans,
                                                  group = centile_cat,
                                                  color = "SLIP",
                                                  linewidth = line_size*2,
                                                  linetype = line_type)) +
                                    geom_line(aes(x = AgeTransformed, y = LMSz_fans,
                                                  group = centile_cat,
                                                  color = "LMSz",
                                                  linewidth = line_size,
                                                  linetype = line_type)) +
                                    scale_linewidth_identity() +
                                    scale_linetype_identity() +
                                    scale_x_continuous(breaks = x_breaks, labels = x_labs) +
                                    ggtitle(pheno_renamed) + theme_pubclean() +
                                    xlab("") + ylab(ylab_text) + labs(colour = "Model") +
                                    scale_colour_manual(values = c("black", "grey")) +
                                    theme(plot.title = element_text(size = 12),
                                          axis.title = element_text(size = 10),
                                          axis.text = element_text(size = 8))
  
}
p1_title <- ggdraw() + draw_label("Males", 
                                  x = 0.5, hjust = 0.5, fontface = "bold")
p1 <- ggarrange(plotlist =  overlap_plots_male[!grepl("SA\\.",overlap_plots_male)], 
                nrow = 1, legend = "none", common.legend = T)
p2_title <- ggdraw() + draw_label("Females", 
                                  x = 0.5, hjust = 0.5, fontface = "bold")
p2 <- ggarrange(plotlist =  overlap_plots_female[!grepl("SA\\.",overlap_plots_male)], 
                nrow = 1, legend = "none", common.legend = T)
p_traj_by_sex <- ggarrange(p1_title, p1, 
                p2_title, p2, 
                nrow = 4, heights = c(0.1,1,0.1,1.2),
                legend = "bottom", common.legend = T)



p_traj_collapsed <- ggarrange(plotlist =  overlap_plots_deriv[!grepl("SA\\.",overlap_plots_deriv)], 
                nrow = 1, legend = "bottom", common.legend = T)

p_traj_collapsed_title <- ggdraw() + draw_label("Overlaid Traj.", angle = 90,
                                  x = 0.5, hjust = 0.5, fontface = "bold")

p_traj_collapsed <- ggarrange(p_traj_collapsed_title, p_traj_collapsed, 
                nrow = 1, ncol = 2, widths = c(0.1,1.2),
                legend = "bottom", common.legend = T)
```

```{r, fig.height = 7.5, fig.width = 11}
p_traj_by_sex
```

```{r, fig.height = 7.5, fig.width = 11}
p_traj_collapsed
```

## Plot Effects

#### Mu

```{r, fig.height = 4.5, fig.width = 7.5}

models$label <- models$feature

lim <- models %>% select(age_coef, sex_coef) %>% abs() %>% max(na.rm = T)
lim <- ceiling(lim*10)/10
plot_lims <- c(-lim,lim)

p_age_effects <- plot_outliers_single(models, 
                           fill_col = "age_coef", 
                           color_scheme = c("royalblue","white","firebrick"),
                           plot_lims = plot_lims, fill_name = "",
                           colorbar_title = "Beta",
                           sig_col = NA, cats = c("GM", "SA","CT", "SUBC"),
                           cort_only = F, add_colorbar = F, add_fillbar = T,
                           exclude_y_label = F, formatted = T, percent = F)

p_sex_effects <- plot_outliers_single(models, 
                           fill_col = "sex_coef", 
                           color_scheme = c("royalblue","white","firebrick"),
                           plot_lims = plot_lims, fill_name = "",
                           colorbar_title = "Beta",
                           sig_col = NA, cats = c("GM", "SA","CT", "SUBC"),
                           cort_only = F, add_colorbar = F, add_fillbar = T,
                           exclude_y_label = F, formatted = T, percent = F)


p_int_effects <- plot_outliers_single(models, 
                           fill_col = "intercept_coef", 
                           color_scheme = c("royalblue","white","firebrick"),
                           plot_lims = plot_lims, fill_name = "",
                           colorbar_title = "Beta",
                           sig_col = NA, cats = c("GM", "SA","CT", "SUBC"),
                           cort_only = F, add_colorbar = F, add_fillbar = T,
                           exclude_y_label = F, formatted = T, percent = F)

p_age_title <- ggdraw() + draw_label("Age", angle = 90,
                                  x = 0.5, hjust = 0.5, fontface = "bold")
p_sex_title <- ggdraw() + draw_label("Sex", angle = 90,
                                  x = 0.5, hjust = 0.5, fontface = "bold")
p_int_title <- ggdraw() + draw_label("Intercept", angle = 90,
                                  x = 0.5, hjust = 0.5, fontface = "bold")

p_age_effects <- ggarrange(p_age_title, p_age_effects, 
                            nrow = 1, ncol = 2, widths = c(0.1,1.2),
                            legend = "bottom", common.legend = T)

p_sex_effects <- ggarrange(p_sex_title, p_sex_effects, 
                            nrow = 1, ncol = 2, widths = c(0.1,1.2),
                            legend = "bottom", common.legend = T)

p_int_effects <- ggarrange(p_int_title, p_int_effects, 
                            nrow = 1, ncol = 2, widths = c(0.1,1.2),
                            legend = "bottom", common.legend = T)

p_effects_mu <- ggarrange(p_age_effects, p_sex_effects, nrow = 2, ncol = 1, 
                            heights = c(1,1), common.legend = T, legend = "bottom")
p_effects_mu
```

#### Sigma

```{r, fig.height = 4.5, fig.width = 8.5}
models$label <- models$feature

lim <- models %>% select(age_sigma_coef, sex_sigma_coef) %>% abs() %>% max(na.rm = T)
lim <- ceiling(lim*10)/10

plot_lims <- c(-lim,lim)

p_age_effects <- plot_outliers_single(models, 
                           fill_col = "age_sigma_coef", 
                           color_scheme = c("royalblue","white","firebrick"),
                           plot_lims = plot_lims, fill_name = "",
                           colorbar_title = "Beta",
                           sig_col = NA, cats = c("GM", "SA","CT", "SUBC"),
                           cort_only = F, add_colorbar = F, add_fillbar = T,
                           exclude_y_label = F, formatted = T, percent = F)

p_sex_effects <- plot_outliers_single(models, 
                           fill_col = "sex_sigma_coef", 
                           color_scheme = c("royalblue","white","firebrick"),
                           plot_lims = plot_lims, fill_name = "",
                           colorbar_title = "Beta",
                           sig_col = NA, cats = c("GM", "SA","CT", "SUBC"),
                           cort_only = F, add_colorbar = F, add_fillbar = T,
                           exclude_y_label = F, formatted = T, percent = F)


p_int_effects <- plot_outliers_single(models, 
                           fill_col = "intercept_sigma_coef", 
                           color_scheme = c("royalblue","white","firebrick"),
                           plot_lims = plot_lims, fill_name = "",
                           colorbar_title = "Beta",
                           sig_col = NA, cats = c("GM", "SA","CT", "SUBC"),
                           cort_only = F, add_colorbar = F, add_fillbar = T,
                           exclude_y_label = F, formatted = T, percent = F)

p_age_title <- ggdraw() + draw_label("Age", angle = 90,
                                  x = 0.5, hjust = 0.5, fontface = "bold")
p_sex_title <- ggdraw() + draw_label("Sex", angle = 90,
                                  x = 0.5, hjust = 0.5, fontface = "bold")
p_int_title <- ggdraw() + draw_label("Intercept", angle = 90,
                                  x = 0.5, hjust = 0.5, fontface = "bold")

p_age_effects <- ggarrange(p_age_title, p_age_effects, 
                            nrow = 1, ncol = 2, widths = c(0.1,1.2),
                            legend = "bottom", common.legend = T)

p_sex_effects <- ggarrange(p_sex_title, p_sex_effects, 
                            nrow = 1, ncol = 2, widths = c(0.1,1.2),
                            legend = "bottom", common.legend = T)

p_int_effects <- ggarrange(p_int_title, p_int_effects, 
                            nrow = 1, ncol = 2, widths = c(0.1,1.2),
                            legend = "bottom", common.legend = T)

p_effects_sigma <- ggarrange(p_age_effects, p_sex_effects, nrow = 2, ncol = 1, 
                            heights = c(1,1), common.legend = T, legend = "bottom")

p_effects_sigma
```

```{r, fig.height = 8.5, fig.width = 8.5}
t1 <- ggdraw() + 
              draw_label(glue('Mu Effects'))
t2 <- ggdraw() + 
              draw_label(glue('Sigma Effects'))
ggarrange(t1, p_effects_mu, t2, p_effects_sigma, nrow = 4, heights = c(0.3,4.2,0.3,4.2))
ggsave("figures/figure_s08_regional_eff.png", bg = "white")
```

## Final Formatted Plot

```{r, fig.height= 12, fig.width=8}
# 4 x 6 plot
  # 4 rows (IDPs)
  # 3 cols (orig, adjusted, overlaid)
  # repeat
# bottom row: exploratory{r, fig.height = 12, fig.width = 12}

leg1 <- get_legend(slip_plots$eTIV + theme(legend.title=element_blank())) %>% as_ggplot()
leg2 <- get_legend(overlap_plots_deriv$eTIV + theme(legend.title=element_blank())) %>% as_ggplot()

plots_final <- list()

for (pheno_of_int in c("eTIV","GMV","sGMV","WMV",
                       "Ventricles","Cerebellum.all",
                       "totalSA","meanCT")) {
  if (pheno_of_int == "eTIV") {
    pheno_label <- "Intracranial Volume"
  } else if (pheno_of_int == "Cerebellum.all") {
    pheno_label <- "Cerebellum"
  } else if (pheno_of_int == "totalSA") {
    pheno_label <- "Cortical Surface Area"
  } else if (pheno_of_int == "meanCT") {
    pheno_label <- "Mean Cortical Thickness"
  } else if (pheno_of_int == "GMV") {
    pheno_label <- "Gray Matter Volume"
  } else if (pheno_of_int == "sGMV") {
    pheno_label <- "Subcortical Gray Matter Volume"
  } else if (pheno_of_int == "WMV") {
    pheno_label <- "White Matter Volume"
  } else {
    pheno_label <- pheno_of_int
  }
  y_scale <- layer_scales(slip_plots[[pheno_of_int]])$y$range$range
  plots <- list(slip_plots[[pheno_of_int]] + ggtitle("Reference"), 
                lmsz_plots[[pheno_of_int]] + ggtitle("22q Adjusted"),
                overlap_plots_deriv[[pheno_of_int]] + ggtitle("Overlap") + scale_y_continuous(limits = y_scale))
  p1 <- ggarrange(plotlist = plots, nrow = 1, ncol = 3, common.legend = T, legend = "none")
  p_title <- ggdraw() + draw_label(pheno_label, fontface = "bold")
  plots_final[[pheno_of_int]] <- ggarrange(p_title, p1, nrow = 2, ncol = 1, heights = c(0.1,1))
}

p1A <- ggarrange(plotlist = plots_final[1:4], nrow = 4, ncol = 1, common.legend = T, 
                 legend = "none")
p1B <- ggarrange(plotlist = plots_final[5:8], nrow = 4, ncol = 1, common.legend = T, 
                 legend = "none")
p1 <- ggarrange(p1A, NULL, p1B, widths = c(1,0.1,1), ncol = 3)

p2 <- ggarrange(NULL, leg1, leg2, NULL, nrow = 1, ncol = 4)

```

```{r, fig.height= 12, fig.width=12}
library(grid)
p <- ggarrange(p1,p2, heights = c(1,0.08), nrow = 2, ncol = 1)
x = c(0.5, 0.5)
y = c(0.08, 0.98)
id = c(1,1)

p
grid.polygon(x,y,id,
             gp = gpar(lty = "solid", lwd = 1, col = "black"))
save(p, file = "additional_plots/lmsz_v2.rdata")
```

## Save Table

```{r}
models_fmt <- models %>% select(-c(m_model, s_model)) %>%
                  mutate(label = case_match(feature,
                                            "Cerebellum.all" ~ "Cerebellum",
                                            "SUBC.Left_Accumbens.area" ~ "SUBC.Left_Accumbens",
                                            "SUBC.Right_Accumbens.area" ~ "SUBC.Right_Accumbens",
                                            .default = feature)) %>%
                  relocate(label, .before = feature) %>%
                  separate_wider_delim(label, delim = ".", names = c("IDP Group", "IDP"),
                                       too_few = "align_end") %>%
                  mutate(`IDP Group` = ifelse(is.na(`IDP Group`), "Global", `IDP Group`),
                         `IDP Group` = factor(`IDP Group`, levels = c("Global","SUBC","GM","SA","CT")),
                         across(contains("_coef"), ~ round(.x, 2)),
                         across(ends_with("IC"), ~ round(.x, 0))) %>%
                  select(-feature, contains("interaction")) %>%
                  arrange(`IDP Group`, IDP)
flextable(models_fmt)
write_csv(models_fmt, "tables/table_s08_lmsz_models.csv")
```

## Plot Global Worm Plots

```{r, fig.height = 6, fig.width = 12}

glob_wps <- slip_worm_plots[global_measures]
for (i in 1:length(global_measures)) {
  glob_wps[[global_measures[i]]] <- glob_wps[[global_measures[i]]] + ggtitle(global_measure_names[i])
}

ggarrange(plotlist = glob_wps, nrow = 2, ncol = 4)
ggsave("figures/figure_s12_wp.png", bg = "white")
```

## Plot All Worm Plots

```{r}
final_worm_plots <- list()

glob_subc_feat <- features[grepl("SUBC\\.",features) | !grepl("GM\\.|SA\\.|CT\\.",features)]
glob_subc_feat <- glob_subc_feat[order(grepl("SUBC\\.",glob_subc_feat))]

for (feature in glob_subc_feat) {
  final_worm_plots[[feature]] <- slip_worm_plots[[feature]] + ggtitle(feature)
}

feat <- unique(str_remove_all(features[!(features %in% glob_subc_feat)],"GM\\.|SA\\.|CT\\.|lh_|rh_"))
# (GM, SA, CT) x (lh, rh) * 4 per page
for (i in feat) {
  for (j in c("GM","SA","CT")) {
    for (k in c("lh","rh")) {
      feat_name <- glue("{j}.{k}_{i}")
      final_worm_plots[[feat_name]] <- slip_worm_plots[[feat_name]] + ggtitle(feat_name)
    }
  }
}

```

```{r}
#| output: false
library(gridExtra)

ggsave(
   filename = glue("additional_plots/lmsz_worm_plots.pdf"), 
   plot = marrangeGrob(final_worm_plots, nrow=8, ncol=6),
   width = 8.5, height = 11
)
```

# Plot All LMSz Charts

```{r, fig.height = 7.5, fig.width = 11}
PLOTS <- list()
features_order <- c("eTIV","GMV","sGMV","WMV","Ventricles","Cerebellum.all","totalSA","meanCT",
                       features[startsWith(features,"GM.")],
                       features[startsWith(features,"SUBC.")],
                       features[startsWith(features,"SA.")],
                       features[startsWith(features,"CT.")])
for (pheno_of_int in features_order) {
  
  if (grepl("CT",pheno_of_int)) {
    x_breaks <- log(c(365.25*2+280, 
                      365.25*6+280, 365.25*21+280))
    x_labs <- c("2y","6y","21y")
    x_lims <- log(c(365.25*2+280, 365.25*21+280))
  } else {
    x_breaks <- log(c(280, 365.25*1+280, 365.25*2+280, 
                      365.25*6+280, 365.25*21+280))
    x_labs <- c("0y","1y","2y","6y","21y")
    x_lims <- log(c(280, 365.25*21+280))
  }
  out_fans_plot <- out_fans_slip %>% filter(pheno == pheno_of_int) %>% filter(AgeTransformed >= x_lims[1],AgeTransformed <= x_lims[2])
  # print(pheno_of_int)
  p1 <- ggplot(out_fans_plot) +
            geom_point(data = df, aes(y = get(glue("{pheno_of_int}Transformed.q.zscore")),
                                      x = AgeTransformed, color=sex, fill=sex), alpha=0.3) +
            geom_line(aes(x = AgeTransformed, y = LMSz_input_fans,
                          group = interaction(centile_cat, sex),
                          color = sex,
                          linewidth = line_size,
                          linetype = line_type)) +
            scale_linewidth_identity() +
            scale_linetype_identity() +
            scale_x_continuous(breaks = x_breaks, labels = x_labs, limits = x_lims) +
            ggtitle("22q LMSz Trajectory") + ylab("Z-Score") +
            theme_pubr() +
            theme(plot.title = element_text(size = 12),
                  axis.title = element_text(size = 10),
                  axis.text = element_text(size = 8))
  
  p2 <- ggplot(out_fans_plot) +
            geom_point(data = df, aes(y = get(glue("{pheno_of_int}Transformed.normalised")),
                                      x = AgeTransformed, color=sex, fill=sex), alpha=0.3) +
            geom_line(aes(x = AgeTransformed, y = SLIP_input_fans,
                          group = interaction(centile_cat, sex),
                          color = sex,
                          linewidth = line_size,
                          linetype = line_type)) +
            scale_linewidth_identity() +
            scale_linetype_identity() +
            scale_x_continuous(breaks = x_breaks, labels = x_labs, limits = x_lims) +
            ggtitle("Original Model") + ylab("Normalized Value") +
            theme_pubr() +
            theme(plot.title = element_text(size = 12),
                  axis.title = element_text(size = 10),
                  axis.text = element_text(size = 8))
  
  p3 <- ggplot(out_fans_plot) +
            geom_point(data = df, aes(y = get(glue("{pheno_of_int}Transformed.normalised")),
                                      x = AgeTransformed, color=sex, fill=sex), alpha=0.3) +
            geom_line(aes(x = AgeTransformed, y = LMSz_fans,
                          group = interaction(centile_cat, sex),
                          color = sex,
                          linewidth = line_size*1.5,
                          linetype = line_type)) +
            scale_linewidth_identity() +
            scale_linetype_identity() +
            scale_x_continuous(breaks = x_breaks, labels = x_labs, limits = x_lims) +
            ggtitle("LMSz Backtransformed") + ylab("Normalized Value") +
            theme_pubr() +
            theme(plot.title = element_text(size = 12),
                  axis.title = element_text(size = 10),
                  axis.text = element_text(size = 8))
  
  olap_plot <- out_fans_plot %>% 
                  filter(pheno == pheno_of_int,
                         centile_cat == "cent_0.5") %>%
                  pivot_longer(c(SLIP_input_fans, LMSz_fans), 
                               names_to = "Model", values_to = "Fans") %>%
                  mutate(Model = str_remove_all(Model, "_input_fans|_fans"))
  
  p4 <- ggplot(olap_plot) +
            geom_line(aes(x = AgeTransformed, y = Fans,
                          group = interaction(sex, Model),
                          color = interaction(sex, Model),
                          linewidth = line_size*1.5,
                          linetype = line_type)) +
            scale_linewidth_identity() +
            scale_linetype_identity() +
            scale_x_continuous(breaks = x_breaks, labels = x_labs, limits = x_lims) +
            scale_color_manual(values = c("#F8766D","#00BFC4","firebrick","royalblue")) +
            ggtitle("Median Lines") + ylab("Normalized Value") +
            theme_pubclean() +
            theme(plot.title = element_text(size = 12),
                  axis.title = element_text(size = 10),
                  axis.text = element_text(size = 8)) +
            labs(color="")
  
  p5 <- slip_worm_plots[[pheno_of_int]]
  p6 <- ggarrange(p1, p2, p3, ncol = 1, legend = "bottom", common.legend = T)
  p_title <- ggdraw() + draw_label(pheno_of_int, fontface = "bold")
  p7 <- ggarrange(p4, p5,ncol = 1, legend = "bottom", common.legend = F)
  p8 <- ggarrange(p6, p7, ncol = 2)
  PLOTS[[pheno_of_int]] <- ggarrange(p_title, p8, ncol = 1, heights = c(0.05,1))
}
```

```{r}
library(gridExtra)

ggsave(
   filename = glue("additional_plots/LMSz_curve_plots.pdf"), 
   plot = marrangeGrob(PLOTS, nrow=1, ncol=1),
   width = 11, height = 8.5
)
```
